name: PHP 8.2 Lint && Tests

on:
  pull_request:

jobs:
  lint:
    name: Linter & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install

      - name: Composer lint
        run: composer lint

      - name: Composer test
        run: composer test
