name: "PHPStan"

on:
  push:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/ --level=9
